import { VerseHighlightColor } from "./verse-type"

export type BookTestamentType = "newTestament" | "oldTestament"

export type LocalStorageBookObject = {
  book1: BookType
  book1Chapter: number
  book1Version: string // TODO - create a type for version type
  book1HighlightedVerses?: VerseHighlightColor[]
  book2?: BookType
  book2Chapter?: number
  book2Version?: string // TODO - create a type for version type
  book2HighlightedVerses?: VerseHighlightColor[]
}

export type BookType = "genesis"
  | "exodus"
  | "leviticus"
  | "numbers"
  | "deuteronomy"
  | "joshua"
  | "judges"
  | "ruth"
  | "1 samuel"
  | "2 samuel"
  | "1 kings"
  | "2 kings"
  | "1 chronicles"
  | "2 chronicles"
  | "ezra"
  | "nehemiah"
  | "esther"
  | "job"
  | "psalms"
  | "proverbs"
  | "ecclesiastes"
  | "song of solomon"
  | "isaiah"
  | "jeremiah"
  | "lamentations"
  | "ezekiel"
  | "daniel"
  | "hosea"
  | "joel"
  | "amos"
  | "obadiah"
  | "jonah"
  | "micah"
  | "nahum"
  | "habakkuk"
  | "zephaniah"
  | "haggai"
  | "zechariah"
  | "malachi"
  | "matthew"
  | "mark"
  | "luke"
  | "john"
  | "acts"
  | "romans"
  | "1 corinthians"
  | "2 corinthians"
  | "galatians"
  | "ephesians"
  | "philippians"
  | "colossians"
  | "1 thessalonians"
  | "2 thessalonians"
  | "1 timothy"
  | "2 timothy"
  | "titus"
  | "philemon"
  | "hebrews"
  | "james"
  | "1 peter"
  | "2 peter"
  | "1 john"
  | "2 john"
  | "3 john"
  | "jude"
  | "revelation";

